"""Matching service for bidirectional job-candidate matching.

Embeddings (resume, job descriptions) are generated by the BGE model and cached
by content hash (see mcf.lib.embeddings.embeddings_cache). Cache is used when
ENABLE_EMBEDDINGS_CACHE=1. TTL: indefinite.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

from datetime import datetime, timezone
from typing import Any

import numpy as np

from mcf.api.config import settings
from mcf.api.active_jobs_pool_cache import (
    compute_ranked_from_pool,
    get_pool_or_fetch,
)
from mcf.lib.classifiers import role_name as _role_name, predict_candidate_tier
from mcf.lib.storage.base import Storage

# Pure semantic matching — skills keyword overlap removed.
# Skills data is too noisy and inconsistently populated to be a reliable signal.
_SEMANTIC_WEIGHT = 1.0
_SKILLS_WEIGHT = 0.0

# Recency factor: gentle penalty for older jobs (0.5% per day, floor 0.5).
# Balances relevance with freshness without filtering out old jobs.
_RECENCY_DECAY_PER_DAY = 0.005
_RECENCY_FLOOR = 0.5

# Rocchio query expansion weights.
# Resume embedding stays dominant (α); liked jobs nudge the query forward (β);
# disliked jobs push it away (γ). γ < β so negative signal doesn't dominate.
_ROCCHIO_ALPHA = 0.7
_ROCCHIO_BETA = 0.3
_ROCCHIO_GAMMA = 0.1
_MIN_LIKED_FOR_EXPANSION = 1

# Tier boost: 5% score multiplier when job's predicted_tier matches candidate's tier.
# Small enough to not override semantic relevance; enough to surface same-tier jobs ahead of
# otherwise-equal cross-tier jobs.
_TIER_BOOST = 1.05


class MatchingService:
    """Service for matching candidates to jobs and vice versa."""

    def __init__(self, store: Storage) -> None:
        self.store = store

    @staticmethod
    def _skills_overlap_score(job_skills: list[str], resume_text_lower: str) -> float:
        """Fraction of a job's skills that appear (as substrings) in the resume.

        Returns a value in [0, 1].  Returns 0 if either input is empty so that
        jobs without skills data do not receive an artificial skills bonus.
        """
        if not job_skills or not resume_text_lower:
            return 0.0
        hits = sum(1 for skill in job_skills if skill.lower() in resume_text_lower)
        return hits / len(job_skills)

    def _build_session(
        self,
        embedding: list[float],
        mode: str,
        user_id: str,
        exclude_interacted: bool,
        exclude_rated_only: bool,
        min_similarity: float,
        max_days_old: int | None,
        allowed_uuids: set[str] | None = None,
        tier_boost_uuids: set[str] | None = None,
    ) -> tuple[str, list[str]]:
        """Run the cheap vector query, score, filter, and create a session.
        Returns (session_id, ranked_ids). ranked_ids are "uuid:score" strings.
        Use 2k pool: applicants typically apply to ~200 max; 2k gives 10x headroom for filters and Load More."""
        if settings.enable_active_jobs_pool_cache:
            pool, matrix = get_pool_or_fetch(self.store)
            ranked_with_meta = compute_ranked_from_pool(pool, embedding, matrix=matrix)  # no cap — all active jobs
        else:
            ranked_with_meta = self.store.get_active_job_ids_ranked(embedding, limit=50_000)
        if not ranked_with_meta:
            return ("", [])

        interacted_jobs: set[str] = set()
        if exclude_interacted and user_id:
            if exclude_rated_only:
                interacted_jobs = set(self.store.get_interested_job_uuids(user_id)) | set(
                    self.store.get_not_interested_job_uuids(user_id)
                )
            else:
                interacted_jobs = self.store.get_interacted_jobs(user_id)

        scored: list[tuple[float, str]] = []
        for job_uuid, distance, last_seen_at in ranked_with_meta:
            if allowed_uuids is not None and job_uuid not in allowed_uuids:
                continue
            if job_uuid in interacted_jobs:
                continue
            similarity = 1.0 - distance

            if min_similarity > 0 and similarity < min_similarity:
                continue

            if max_days_old is not None and last_seen_at:
                ts = last_seen_at if last_seen_at.tzinfo else last_seen_at.replace(tzinfo=timezone.utc)
                if (datetime.now(timezone.utc) - ts).days > max_days_old:
                    continue

            days_old = 0
            if last_seen_at:
                ts = last_seen_at if last_seen_at.tzinfo else last_seen_at.replace(tzinfo=timezone.utc)
                days_old = max(0, (datetime.now(timezone.utc) - ts).days)
            recency_factor = max(_RECENCY_FLOOR, 1.0 - _RECENCY_DECAY_PER_DAY * days_old)
            tier_factor = _TIER_BOOST if (tier_boost_uuids is not None and job_uuid in tier_boost_uuids) else 1.0
            combined_score = similarity * recency_factor * tier_factor
            scored.append((combined_score, job_uuid))

        scored.sort(reverse=True, key=lambda x: x[0])
        ranked_entries = [f"{uuid}:{score:.6f}" for score, uuid in scored]
        session_id = self.store.create_match_session(
            user_id=user_id, mode=mode, ranked_ids=ranked_entries
        )
        return session_id, ranked_entries

    def _parse_ranked_entries(self, entries: list[str]) -> list[tuple[str, float]]:
        """Parse 'uuid:score' strings to (uuid, score) tuples."""
        result = []
        for entry in entries:
            if ":" in entry:
                uuid, score_str = entry.rsplit(":", 1)
                try:
                    result.append((uuid, float(score_str)))
                except ValueError:
                    result.append((uuid, 0.0))
            else:
                result.append((entry, 0.0))
        return result

    def _expand_query_with_interactions(
        self,
        resume_emb: list[float],
        user_id: str,
    ) -> list[float]:
        """Rocchio query expansion: blend resume embedding with liked/disliked job centroids.

        q_opt = α * resume + β * mean(liked) - γ * mean(disliked)

        Falls back to resume_emb unchanged if the user has no liked jobs or
        embeddings are unavailable. Disliked component is applied independently
        and only if disliked embeddings are retrievable.
        """
        liked_uuids = self.store.get_interested_job_uuids(user_id)
        if len(liked_uuids) < _MIN_LIKED_FOR_EXPANSION:
            return resume_emb

        try:
            liked_pairs = self.store.get_job_embeddings_for_uuids(liked_uuids)
        except Exception:
            return resume_emb
        if not liked_pairs:
            return resume_emb

        q = np.array(resume_emb, dtype=np.float32)

        # Positive centroid
        liked_matrix = np.array([emb for _, emb in liked_pairs], dtype=np.float32)
        liked_mean = liked_matrix.mean(axis=0)
        norm = float(np.linalg.norm(liked_mean))
        if norm > 0:
            liked_mean = liked_mean / norm

        expanded = _ROCCHIO_ALPHA * q + _ROCCHIO_BETA * liked_mean

        # Negative centroid (best-effort — never blocks the positive expansion)
        try:
            disliked_uuids = self.store.get_not_interested_job_uuids(user_id)
            if disliked_uuids:
                disliked_pairs = self.store.get_job_embeddings_for_uuids(disliked_uuids)
                if disliked_pairs:
                    disliked_matrix = np.array([emb for _, emb in disliked_pairs], dtype=np.float32)
                    disliked_mean = disliked_matrix.mean(axis=0)
                    dnorm = float(np.linalg.norm(disliked_mean))
                    if dnorm > 0:
                        disliked_mean = disliked_mean / dnorm
                    expanded = expanded - _ROCCHIO_GAMMA * disliked_mean
        except Exception:
            pass  # disliked component is optional

        # Re-normalise so cosine similarity math still holds
        exp_norm = float(np.linalg.norm(expanded))
        if exp_norm > 0:
            expanded = expanded / exp_norm

        return expanded.tolist()

    def match_candidate_to_jobs(
        self,
        profile_id: str,
        top_k: int = 25,
        offset: int = 0,
        exclude_interacted: bool = True,
        exclude_rated_only: bool = False,
        user_id: str | None = None,
        min_similarity: float = 0.0,
        max_days_old: int | None = None,
        session_id: str | None = None,
        role_clusters: list[int] | None = None,
        predicted_tiers: list[str] | None = None,
    ) -> tuple[list[dict[str, Any]], int, str, str | None]:
        """Find top matching jobs for a candidate using semantic similarity."""
        candidate_emb = self.store.get_candidate_embedding(profile_id)
        if not candidate_emb:
            return ([], 0, "")

        profile = self.store.get_profile_by_profile_id(profile_id)
        if exclude_interacted and user_id is None and profile:
            user_id = profile.get("user_id")

        ranked_entries: list[str] = []
        total = 0

        if session_id and user_id:
            session = self.store.get_match_session(session_id, user_id)
            if session:
                ranked_entries = session["ranked_ids"]
                total = session["total"]

        # Infer candidate's experience tier from their resume embedding (best-effort)
        candidate_tier: str | None = None
        try:
            candidate_tier = predict_candidate_tier(candidate_emb)
        except Exception:
            pass

        if not ranked_entries:
            query_emb = candidate_emb
            if user_id:
                query_emb = self._expand_query_with_interactions(candidate_emb, user_id)
            allowed_uuids = self.store.get_job_uuids_for_filter(role_clusters, predicted_tiers)
            # Fetch UUIDs of jobs matching the candidate's tier for the score boost
            tier_boost_uuids: set[str] | None = None
            if candidate_tier:
                try:
                    tier_boost_uuids = self.store.get_job_uuids_for_filter(
                        predicted_tiers=[candidate_tier]
                    )
                except Exception:
                    pass
            session_id, ranked_entries = self._build_session(
                query_emb,
                "resume",
                user_id or "",
                exclude_interacted,
                exclude_rated_only,
                min_similarity,
                max_days_old,
                allowed_uuids,
                tier_boost_uuids,
            )
            total = len(ranked_entries)

        parsed = self._parse_ranked_entries(ranked_entries)
        page = parsed[offset : offset + top_k]
        page_ids = [uuid for uuid, _ in page]
        scores_by_uuid = {uuid: score for uuid, score in page}

        jobs_map = {j["job_uuid"]: j for j in self.store.get_jobs_by_uuids(page_ids)}

        results = []
        for job_uuid in page_ids:
            job = jobs_map.get(job_uuid)
            if not job:
                continue
            combined_score = scores_by_uuid.get(job_uuid, 0.0)
            rc = job.get("role_cluster")
            results.append(
                {
                    "job_uuid": job_uuid,
                    "title": job.get("title"),
                    "company_name": job.get("company_name"),
                    "location": job.get("location"),
                    "job_url": job.get("job_url"),
                    "similarity_score": combined_score,
                    "semantic_score": combined_score,
                    "job_skills": job.get("skills") or [],
                    "last_seen_at": job.get("last_seen_at"),
                    "role_cluster": rc,
                    "role_name": _role_name(rc) if rc is not None else None,
                    "predicted_tier": job.get("predicted_tier"),
                    "role_clusters": job.get("role_clusters"),
                    "salary_min": job.get("salary_min"),
                    "salary_max": job.get("salary_max"),
                }
            )

        return (results, total, session_id or "", candidate_tier)

    # ------------------------------------------------------------------
    # Taste-profile methods
    # ------------------------------------------------------------------

    def compute_and_store_taste(self, profile_id: str, user_id: str) -> dict:
        """Build a taste-profile embedding from the user's Interested/Not Interested ratings.

        Algorithm:
            positive  = mean embedding of all "interested" jobs
            negative  = mean embedding of all "not_interested" jobs  (may be empty)
            taste_raw = positive - 0.3 * negative
            taste_vec = L2_normalize(taste_raw)

        The result is stored via ``store.upsert_taste_embedding`` and also
        returned as a dict so the caller can surface stats to the frontend.

        Returns ``{"ok": True, "rated_count": N, "interested": P, "not_interested": Q}``
        or ``{"ok": False, "reason": "..."}`` if not enough data.
        """
        interested_uuids = self.store.get_interested_job_uuids(user_id)
        not_interested_uuids = self.store.get_not_interested_job_uuids(user_id)

        if not interested_uuids:
            return {"ok": False, "reason": "No 'interested' ratings yet. Rate at least one job as Interested first."}

        try:
            pos_pairs = self.store.get_job_embeddings_for_uuids(interested_uuids)
        except Exception as e:
            logger.exception("get_job_embeddings_for_uuids failed: %s", e)
            return {"ok": False, "reason": "Failed to load job embeddings. Please try again."}

        if not pos_pairs:
            return {"ok": False, "reason": "Interested jobs have no embeddings yet."}

        try:
            pos_matrix = np.array([emb for _, emb in pos_pairs], dtype=np.float32)
        except (ValueError, TypeError) as e:
            logger.warning("Invalid embedding data in taste computation: %s", e)
            return {"ok": False, "reason": "Invalid embedding data. Re-run crawl to refresh."}
        positive_mean = pos_matrix.mean(axis=0)

        taste_raw = positive_mean.copy()

        if not_interested_uuids:
            try:
                neg_pairs = self.store.get_job_embeddings_for_uuids(not_interested_uuids)
            except Exception as e:
                logger.warning("get_job_embeddings_for_uuids (neg) failed: %s", e)
                neg_pairs = []
            if neg_pairs:
                neg_matrix = np.array([emb for _, emb in neg_pairs], dtype=np.float32)
                negative_mean = neg_matrix.mean(axis=0)
                taste_raw = taste_raw - 0.3 * negative_mean

        # L2 normalise so dot-product == cosine similarity during matching
        norm = float(np.linalg.norm(taste_raw))
        if norm > 0:
            taste_vec = (taste_raw / norm).tolist()
        else:
            taste_vec = positive_mean.tolist()

        model_name = self.store.get_embedding_model_name() or "BAAI/bge-base-en-v1.5"

        self.store.upsert_taste_embedding(
            profile_id=profile_id,
            model_name=model_name,
            embedding=taste_vec,
        )

        return {
            "ok": True,
            "interested": len(pos_pairs),
            "not_interested": len(not_interested_uuids),
            "rated_count": len(interested_uuids) + len(not_interested_uuids),
        }

    def match_taste_to_jobs(
        self,
        profile_id: str,
        top_k: int = 25,
        offset: int = 0,
        exclude_rated: bool = True,
        user_id: str | None = None,
        min_similarity: float = 0.0,
        max_days_old: int | None = None,
        session_id: str | None = None,
        role_clusters: list[int] | None = None,
        predicted_tiers: list[str] | None = None,
    ) -> tuple[list[dict[str, Any]], int, str]:
        """Find top jobs matching the user's taste-profile embedding."""
        taste_emb = self.store.get_taste_embedding(profile_id)
        if not taste_emb:
            return ([], 0, "")

        ranked_entries: list[str] = []
        total = 0

        if session_id and user_id:
            session = self.store.get_match_session(session_id, user_id)
            if session:
                ranked_entries = session["ranked_ids"]
                total = session["total"]

        if not ranked_entries:
            allowed_uuids = self.store.get_job_uuids_for_filter(role_clusters, predicted_tiers)
            session_id, ranked_entries = self._build_session(
                taste_emb,
                "taste",
                user_id or "",
                exclude_rated,
                True,  # taste always excludes only interested/not_interested
                min_similarity,
                max_days_old,
                allowed_uuids,
            )
            total = len(ranked_entries)

        parsed = self._parse_ranked_entries(ranked_entries)
        page = parsed[offset : offset + top_k]
        page_ids = [uuid for uuid, _ in page]
        scores_by_uuid = {uuid: score for uuid, score in page}

        jobs_map = {j["job_uuid"]: j for j in self.store.get_jobs_by_uuids(page_ids)}

        results = []
        for job_uuid in page_ids:
            job = jobs_map.get(job_uuid)
            if not job:
                continue
            combined_score = scores_by_uuid.get(job_uuid, 0.0)
            rc = job.get("role_cluster")
            results.append(
                {
                    "job_uuid": job_uuid,
                    "title": job.get("title"),
                    "company_name": job.get("company_name"),
                    "location": job.get("location"),
                    "job_url": job.get("job_url"),
                    "similarity_score": combined_score,
                    "job_skills": job.get("skills") or [],
                    "last_seen_at": job.get("last_seen_at"),
                    "role_cluster": rc,
                    "role_name": _role_name(rc) if rc is not None else None,
                    "predicted_tier": job.get("predicted_tier"),
                    "role_clusters": job.get("role_clusters"),
                    "salary_min": job.get("salary_min"),
                    "salary_max": job.get("salary_max"),
                }
            )

        return (results, total, session_id or "")
